######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

title: '&lCài Đặt Đảo'
previous-menu: true

pattern:
  - '$ $ $ $ $ $ $ $ $'
  - '$ @ @ @ @ @ @ @ $'
  - '$ @ @ @ @ @ @ @ $'
  - '$ @ @ @ @ @ @ @ $'
  - '$ $ % $ * $ ^ $ $'

slots: '@'
previous-page: '%'
current-page: '*'
next-page: '^'

items:
  '$':
    type: CYAN_STAINED_GLASS_PANE
    name: '&f'
  '%':
    type: PAPER
    name: '{0}Trang Trước'
  '*':
    type: SUNFLOWER
    name: '&aTrang Hiện Tại'
    lore:
      - '&7Trang {0}'
  '^':
    type: PAPER
    name: '{0}Trang Sau'

settings:
  always_day:
    display-menu: true
    settings-enabled:
      type: YELLOW_TERRACOTTA
      name: '&6Luôn Là Ban Ngày'
      lore:
        - '&7Đặt thời gian ban ngày trên đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: YELLOW_TERRACOTTA
      name: '&6Luôn Là Ban Ngày'
      lore:
        - '&7Đặt thời gian ban ngày trên đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_middle_day:
    display-menu: true
    settings-enabled:
      type: ORANGE_TERRACOTTA
      name: '&6Luôn Là Giữa Ban Ngày'
      lore:
        - '&7Đặt thời gian giữa ban ngày trên đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: ORANGE_TERRACOTTA
      name: '&6Luôn Là Giữa Ban Ngày'
      lore:
        - '&7Đặt thời gian giữa ban ngày trên đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_night:
    display-menu: true
    settings-enabled:
      type: LIGHT_BLUE_TERRACOTTA
      name: '&6Luôn Là Ban Đêm'
      lore:
        - '&7Đặt thời gian ban đêm trên đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: LIGHT_BLUE_TERRACOTTA
      name: '&6Luôn Là Ban Đêm'
      lore:
        - '&7Đặt thời gian ban đêm trên đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_middle_night:
    display-menu: true
    settings-enabled:
      type: BLUE_TERRACOTTA
      name: '&6Luôn Là Giữa Ban Đêm'
      lore:
        - '&7Đặt thời gian giữa đêm trên đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: BLUE_TERRACOTTA
      name: '&6Luôn Là Giữa Ban Đêm'
      lore:
        - '&7Đặt thời gian giữa đêm trên đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_rain:
    display-menu: true
    settings-enabled:
      type: LILY_PAD
      name: '&6Luôn Luôn Mưa'
      lore:
        - '&7Đặt thời tiết mưa trên đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: LILY_PAD
      name: '&6Luôn Luôn Mưa'
      lore:
        - '&7Đặt thời tiết mưa trên đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_shiny:
    display-menu: true
    settings-enabled:
      type: DEAD_BUSH
      name: '&6Luôn Luôn Nắng'
      lore:
        - '&7Đặt thời tiết nắng trên đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: DEAD_BUSH
      name: '&6Luôn Luôn Nắng'
      lore:
        - '&7Đặt thời tiết nắng trên đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  creeper_explosion:
    display-menu: true
    settings-enabled:
      type: CREEPER_HEAD
      name: '&6Nổ Creeper'
      lore:
        - '&7Cho phép creeper phá block trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: CREEPER_HEAD
      name: '&6Nổ Creeper'
      lore:
        - '&7Cho phép creeper phá block trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  crops_growth:
    display-menu: true
    settings-enabled:
      type: WHEAT_SEEDS
      name: '&6Sự Phát Triển Cây Trồng'
      lore:
        - '&7Cho phép cây trồng phát triển trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: WHEAT_SEEDS
      name: '&6Sự Phát Triển Cây Trồng'
      lore:
        - '&7Cho phép cây trồng phát triển trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  egg_lay:
    display-menu: true
    settings-enabled:
      type: EGG
      name: '&6Gà Đẻ Trứng'
      lore:
        - '&7Cho phép gà đẻ trứng trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: EGG
      name: '&6Gà Đẻ Trứng'
      lore:
        - '&7Cho phép gà đẻ trứng trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  enderman_grief:
    display-menu: true
    settings-enabled:
      type: ENDER_PEARL
      name: '&6Enderman Lấy Cắp Block'
      lore:
        - '&7Cho phép enderman lấy cắp block trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: ENDER_PEARL
      name: '&6Enderman Lấy Cắp Block'
      lore:
        - '&7Cho phép enderman lấy cắp block trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  fire_spread:
    display-menu: true
    settings-enabled:
      type: FLINT_AND_STEEL
      name: '&6Lửa Lan'
      lore:
        - '&7Cho phép lửa lan trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: FLINT_AND_STEEL
      name: '&6Lửa Lan'
      lore:
        - '&7Cho phép lửa lan trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  ghast_fireball:
    display-menu: true
    settings-enabled:
      type: FIRE_CHARGE
      name: '&6Cầu Lửa Ghast'
      lore:
        - '&7Cho phép cầu lửa phá block trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: FIRE_CHARGE
      name: '&6Cầu Lửa Ghast'
      lore:
        - '&7Cho phép cầu lửa phá block trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  lava_flow:
    display-menu: true
    settings-enabled:
      type: LAVA_BUCKET
      name: '&6Dung Nham Chảy'
      lore:
        - '&7Cho phép dung nham chảy trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: LAVA_BUCKET
      name: '&6Dung Nham Chảy'
      lore:
        - '&7Cho phép dung nham chảy trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  natural_animals_spawn:
    display-menu: true
    settings-enabled:
      type: PIG_SPAWN_EGG
      name: '&6Động Vật Sinh Ra Tự Nhiên'
      lore:
        - '&7Cho phép động vật sinh ra tự nhiên trong đảo.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: PIG_SPAWN_EGG
      name: '&6Động Vật Sinh Ra Tự Nhiên'
      lore:
        - '&7Cho phép động vật sinh ra tự nhiên trong đảo.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  natural_monster_spawn:
    display-menu: true
    settings-enabled:
      type: ZOMBIE_SPAWN_EGG
      name: '&6Quái Vật Sinh Ra Tự Nhiên'
      lore:
        - '&7Cho phép quái vật sinh ra tự nhiên trong đảo.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: ZOMBIE_SPAWN_EGG
      name: '&6Quái Vật Sinh Ra Tự Nhiên'
      lore:
        - '&7Cho phép quái vật sinh ra tự nhiên trong đảo.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  pvp:
    display-menu: true
    settings-enabled:
      type: DIAMOND_SWORD
      name: '&6PvP'
      lore:
        - '&7Cho phép người chơi PvP trong đảo.'
        - '&7Hiện tại: &aBẬT&7.'
      flags:
        - HIDE_ATTRIBUTES
    settings-disabled:
      type: DIAMOND_SWORD
      name: '&6PvP'
      lore:
        - '&7Cho phép người chơi PvP trong đảo.'
        - '&7Hiện tại: &cTẮT&7.'
      flags:
        - HIDE_ATTRIBUTES
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  spawner_animals_spawn:
    display-menu: true
    settings-enabled:
      type: SPAWNER
      name: '&6Spawner Sinh Động Vật'
      lore:
        - '&7Cho phép spawner sinh động vật trong đảo.'
        - '&7Hiện tại: &aBẬT&7.'
      flags:
        - HIDE_ADDITIONAL_TOOLTIP
    settings-disabled:
      type: SPAWNER
      name: '&6Spawner Sinh Động Vật'
      lore:
        - '&7Cho phép spawner sinh động vật trong đảo.'
        - '&7Hiện tại: &cTẮT&7.'
      flags:
        - HIDE_ADDITIONAL_TOOLTIP
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  spawner_monster_spawn:
    display-menu: true
    settings-enabled:
      type: SPAWNER
      name: '&6Spawner Sinh Quái Vật'
      lore:
        - '&7Cho phép spawner sinh quái vật trong đảo.'
        - '&7Hiện tại: &aBẬT&7.'
      flags:
        - HIDE_ADDITIONAL_TOOLTIP
    settings-disabled:
      type: SPAWNER
      name: '&6Spawner Sinh Quái Vật'
      lore:
        - '&7Cho phép spawner sinh quái vật trong đảo.'
        - '&7Hiện tại: &cTẮT&7.'
      flags:
        - HIDE_ADDITIONAL_TOOLTIP
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  tnt_explosion:
    display-menu: true
    settings-enabled:
      type: TNT
      name: '&6Nổ TNT'
      lore:
        - '&7Cho phép TNT phá block trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: TNT
      name: '&6Nổ TNT'
      lore:
        - '&7Cho phép TNT phá block trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  tree_growth:
    display-menu: true
    settings-enabled:
      type: OAK_SAPLING
      name: '&6Sự Phát Triển Cây'
      lore:
        - '&7Cho phép cây phát triển trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: OAK_SAPLING
      name: '&6Sự Phát Triển Cây'
      lore:
        - '&7Cho phép cây phát triển trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  water_flow:
    display-menu: true
    settings-enabled:
      type: WATER_BUCKET
      name: '&6Nước Chảy'
      lore:
        - '&7Cho phép nước chảy trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: WATER_BUCKET
      name: '&6Nước Chảy'
      lore:
        - '&7Cho phép nước chảy trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  wither_explosion:
    display-menu: true
    settings-enabled:
      type: WITHER_SKELETON_SKULL
      name: '&6Nổ Wither'
      lore:
        - '&7Cho phép wither phá block trong đảo của bạn.'
        - '&7Hiện tại: &aBẬT&7.'
    settings-disabled:
      type: WITHER_SKELETON_SKULL
      name: '&6Nổ Wither'
      lore:
        - '&7Cho phép wither phá block trong đảo của bạn.'
        - '&7Hiện tại: &cTẮT&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2