######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##              Trophy Hall - Elysium               ##
##                                                  ##
######################################################

enabled: true

# Tỉ lệ rơi trophy khi đánh bại Mini Boss (%).
drop-chance: 35.0

# particle: Loại hiệu ứng Particle bao quanh trophy (vd: FLAME, PORTAL, CLOUD, END_ROD)
trophies:
  tornado:
    name: 'Lốc Xoáy Tàn Phá'
    material: 'PLAYER_HEAD'
    texture: ''
    particle: 'CLOUD'
    buffs:
      potions:
        - 'FAST_DIGGING:2'
        - 'SPEED:1'
  volcano:
    name: 'Trái Tim Núi Lửa'
    material: 'PLAYER_HEAD'
    texture: ''
    particle: 'FLAME'
    buffs:
      potions:
        - 'FIRE_RESISTANCE:1'
        - 'DAMAGE_RESISTANCE:1'
      bonuses:
        mob-drops: 0.05
  ancient-tree:
    name: 'Dryad Cổ Đại'
    material: 'PLAYER_HEAD'
    texture: ''
    particle: 'VILLAGER_HAPPY'
    buffs:
      potions:
        - 'REGENERATION:1'
      bonuses:
        crop-growth: 0.1
  celestial:
    name: 'Mảnh Thiên Thể'
    material: 'PLAYER_HEAD'
    texture: ''
    particle: 'END_ROD'
    buffs:
      potions:
        - 'NIGHT_VISION:1'
        - 'JUMP:2'
  invasion:
    name: 'Kẻ Xâm Lược'
    material: 'PLAYER_HEAD'
    texture: ''
    particle: 'SMOKE_LARGE'
    buffs:
      potions:
        - 'INCREASE_DAMAGE:1'
      bonuses:
        mob-drops: 0.1
  meteor-shower:
    name: 'Thiên Thạch Rực Cháy'
    material: 'PLAYER_HEAD'
    texture: ''
    particle: 'DRIP_LAVA'
    buffs:
      potions:
        - 'FAST_DIGGING:3'
        - 'FIRE_RESISTANCE:1'
  space-rift:
    name: 'Cổng Không Gian'
    material: 'PLAYER_HEAD'
    texture: ''
    particle: 'PORTAL'
    buffs:
      potions:
        - 'SPEED:2'
      bonuses:
        crop-growth: 0.05
